### ISSUE TITLE
karaf Error executing command

### ISSUE THREAD

**Issue by benzeng** [xipki/xipki#110]
Hi Lijun,

When I start xipki client, report there is no TLS client certificate  present, and can not execute any command, can you help? thanks

karaf@root()> ca-info
Error executing command: remote management is not permitted if TLS client certificate is not present

**Comment by xipki** [comment]
Could you please provide the steps to reproduce this error? Which OS and Version of xipki do you use? Please also attach the log file of xipki-cli (data/log/karaf.log).

**Comment by benzeng** [comment]
Hi,

After finished installation, then try to run xipki client to setup , and can not execute any command just the error.

I build from source code, the version is xipki-cli-5.3.1-SNAPSHOT. 

2019-06-08T23:37:42,707 | INFO  | Blueprint Extender: 3 | BlueprintContainerImpl            446 | 12 - org.apache.aries.blueprint.core - 1.10.2 | Blueprint bundle org.xipki.ocsp-client/5.3.1.SNAPSHOT has been started
2019-06-08T23:37:42,727 | INFO  | Blueprint Extender: 2 | CommandExtension                  146 | 20 - org.apache.karaf.shell.core - 4.2.5 | Registering commands for bundle org.xipki.shell.cmpclient-shell/5.3.1.SNAPSHOT
2019-06-08T23:37:42,730 | INFO  | Blueprint Extender: 2 | BlueprintContainerImpl            446 | 12 - org.apache.aries.blueprint.core - 1.10.2 | Blueprint bundle org.xipki.cmpclient/5.3.1.SNAPSHOT has been started
2019-06-08T23:37:44,551 | ERROR | Karaf local console user karaf | ShellUtil                         152 | 20 - org.apache.karaf.shell.core - 4.2.5 | Exception caught while executing command
org.xipki.ca.api.mgmt.CaMgmtException: remote management is not permitted if TLS client certificate is not present
        at org.xipki.ca.mgmt.client.CaMgmtClient.transmit(CaMgmtClient.java:840) ~[?:?]
        at org.xipki.ca.mgmt.client.CaMgmtClient.transmit(CaMgmtClient.java:771) ~[?:?]
        at org.xipki.ca.mgmt.client.CaMgmtClient.getNames(CaMgmtClient.java:260) ~[?:?]
        at org.xipki.ca.mgmt.client.CaMgmtClient.getSuccessfulCaNames(CaMgmtClient.java:246) ~[?:?]
        at org.xipki.ca.mgmt.shell.CaActions$CaInfo.execute0(CaActions.java:567) ~[?:?]
        at org.xipki.shell.XiAction.execute(XiAction.java:64) ~[?:?]
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) ~[?:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) ~[?:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-06-08T23:37:56,916 | INFO  | FelixShutdown    | BlueprintExtender                 334 | 12 - org.apache.aries.blueprint.core - 1.10.2 | Destroying container for blueprint bundle org.xipki.cmpclient/5.3.1.SNAPSHOT
2019-06-08T23:37:56,918 | INFO  | FelixShutdown    | CommandExtension                  146 | 20 - org.apache.karaf.shell.core - 4.2.5 | Unregistering commands for bundle org.xipki.shell.cmpclient-shell/5.3.1.SNAPSHOT
2019-06-08T23:37:56,921 | INFO  | FelixShutdown    | BlueprintExtender                 334 | 12 - org.apache.aries.blueprint.core - 1.10.2 | Destroying cont

**Comment by benzeng** [comment]
I think the resaon is there is no TLS client certificate when sending HTTPS packet to CA servlet.
where can I setup this parameter ?

thanks

**Comment by benzeng** [comment]
Here is the LOG:
[karaf.log](https://github.com/xipki/xipki/files/3269180/karaf.log)

**Comment by xipki** [comment]
Did you configure the conf/server.xml as in https://github.com/xipki/xipki/blob/master/assemblies/ca-war/README.md?

**Comment by benzeng** [comment]
Yes, I setup as your guide, but still don't work.

Now, I try Jetty, everything goes well, but xipki client still get error:

karaf@root()> ca-info
Error executing command: IOException while sending message to the server: Broken pipe (Write failed)

And I do not know what's the meaning about setup xipki client:
Adapt the CMP client configuration xipki/cmpclient/cmpclient.json

Can you give me the detail about setting cmpclient.json?

Thanks.

**Comment by benzeng** [comment]
2019-06-10T13:11:52,281 | INFO  | Blueprint Extender: 1 | BlueprintContainerImpl            446 | 12 - org.apache.aries.blueprint.core - 1.10.2 | Blueprint bundle org.xipki.cmpclient/5.3.0 has been started
2019-06-10T13:11:54,985 | ERROR | Karaf local console user karaf | ShellUtil                         152 | 20 - org.apache.karaf.shell.core - 4.2.5 | Exception caught while executing command
org.xipki.ca.api.mgmt.CaMgmtException: IOException while sending message to the server: Broken pipe (Write failed)
        at org.xipki.ca.mgmt.client.CaMgmtClient.transmit(CaMgmtClient.java:844) ~[?:?]
        at org.xipki.ca.mgmt.client.CaMgmtClient.transmit(CaMgmtClient.java:770) ~[?:?]
        at org.xipki.ca.mgmt.client.CaMgmtClient.getNames(CaMgmtClient.java:259) ~[?:?]
        at org.xipki.ca.mgmt.client.CaMgmtClient.getSuccessfulCaNames(CaMgmtClient.java:245) ~[?:?]
        at org.xipki.ca.mgmt.shell.CaActions$CaInfo.execute0(CaActions.java:566) ~[?:?]
        at org.xipki.shell.XiAction.execute(XiAction.java:63) ~[?:?]
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) ~[?:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) ~[?:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:?]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:?]
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431) ~[?:?]
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:417) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:879) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:850) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:720) ~[?:?]
        at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1144) ~[?:?]
        at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1280) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1190) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:369) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[?:?]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259) ~[?:?]
        at org.xipki.ca.mgmt.client.CaMgmtClient.transmit(CaMgmtClient.java:800) ~[?:?]
        ... 18 more
2019-06-10T13:17:22,288 | INFO  | FelixShutdown    | BlueprintExtender                 334 | 12 - org.apache.aries.blueprint.core - 1.10.2 | Destroying container for blueprint bundle org.xipki.ocsp-client/5.3.0

**Comment by xipki** [comment]
It seems, in both tomcat and jetty, that the server's HTTPS id not started/configured correctly. Please take a look in the log files.

**Comment by benzeng** [comment]
![image](https://user-images.githubusercontent.com/6300102/59177397-956bd600-8b8e-11e9-9e05-b001ee6f4af5.png)

Open in browser got the result above.  any wrong ? thanks

**Comment by xipki** [comment]
Please drop me an Email with your What's app or wechat Account.

**Comment by benzeng** [comment]
Hi,

My WeChat account is: eyetalk

Thanks

**Comment by xipki** [comment]
For jetty 9.4.15 - 9.4.18
  There is a bug in these versions, you need to remove the `default="HTTPS"` block from the 
  line `EndpointIdentificationAlgorithm` in the file `etc/jetty-ssl-context.xml`, namely from

```
 <Set name="EndpointIdentificationAlgorithm"><Property name="jetty.sslContext.endpointIdentificationAlgorithm" default="HTTPS"/></Set>
```
to

```
 <Set name="EndpointIdentificationAlgorithm"><Property name="jetty.sslContext.endpointIdentificationAlgorithm"/></Set>
```

**Comment by xipki** [comment]
For tomcat, please use versions 8.5.* or 9.*.

**Comment by benzeng** [comment]
It Works, thanks !
