### ISSUE TITLE
Getting OCSP Responder error - OCSP routines:PARSE_HTTP_LINE1:server response error:ocsp_ht.c:314:Code=404

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#113]
Hi,

I have been away from the XiPKI instance that I had built a couple of weeks ago, but I am back to work on it today, but when I try to perform an "openssl ocsp" test, I am getting an error:

openssl ocsp -VAfile ocsp-signer.pem -url http://localhost:8080 -issuer XXX_41.pem -serial 0x2FFFFD
Error querying OCSP responder
139993067874208:error:27076072:OCSP routines:PARSE_HTTP_LINE1:server response error:ocsp_ht.c:314:Code=404

I thought that might be because of the CRLs expired, so I copied in two updated CRLs, and I added the UPDATEME file in the two crl-XXX directories, but the UPDATEME files are not changing to UPDATEME.SUCC or FAIL, so it doesn't look like the crls are being update in XiPKI?

I have tried bouncing the Tomcat (several times, actually) but still get the same behavior/problems.

What else might be causing these problems (and how to diagnose)?

Thanks,
Jim

**Comment by ohaya** [comment]
This seems similar to what happened awhile ago, see:

https://github.com/xipki/xipki/issues/107#issuecomment-498439929

In that case, it just started working, mysteriously.

FYI, the UPDATEME files still not changed and I have bounced the Tomcat and even rebooted the server.

Does the process for updating the CRL look at anything other than the presence of the UPDATEME?  Like does it check/compare the dates for the files, etc.  It seems like there is some other condition for updating?

Jim

**Comment by xipki** [comment]
The client got an 404 error. Could you please upload the tomcat log file *access* and the OCSP server log file?

**Comment by ohaya** [comment]
Here's the localhost_access log:

[root@ip-192-168-159-105 logs]# cat localhost_access_log.2019-07-02.txt
127.0.0.1 - - [02/Jul/2019:14:35:44 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:36:15 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:36:49 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:37:34 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:39:06 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:39:06 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:45:26 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:45:26 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:46:19 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:50:20 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:14:50:20 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:15:51:34 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:16:02:30 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:16:10:54 -0400] "POST / HTTP/1.0" 404 1078
127.0.0.1 - - [02/Jul/2019:16:23:26 -0400] "POST / HTTP/1.0" 404 1078

**Comment by ohaya** [comment]
the <TOMCAT>/logs/ocsp.log is dated 6/12/2019 (like a couple weeks old).

**Comment by ohaya** [comment]
I just noticed these from the catalina.out from earlier today:

02-Jul-2019 16:10:30.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/apps/apache-tomcat-9.0.20
02-Jul-2019 16:10:30.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/apps/apache-tomcat-9.0.20/temp
02-Jul-2019 16:10:30.969 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
02-Jul-2019 16:10:31.256 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
02-Jul-2019 16:10:31.272 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[HTTP/1.1-8080]]
        org.apache.catalina.LifecycleException: Protocol handler initialization failed
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:983)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.core.StandardService.initInternal(StandardService.java:533)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1059)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:584)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:607)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:304)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
        Caused by: java.net.BindException: Address already in use
                at sun.nio.ch.Net.bind0(Native Method)
                at sun.nio.ch.Net.bind(Net.java:433)
                at sun.nio.ch.Net.bind(Net.java:425)
                at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
                at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
                at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:248)
                at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:222)
                at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1119)
                at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1132)
                at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:557)
                at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:74)
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:980)
                ... 13 more
02-Jul-2019 16:10:31.273 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
02-Jul-2019 16:10:31.274 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[AJP/1.3-8009]]
        org.apache.catalina.LifecycleException: Protocol handler initialization failed
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:983)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.core.StandardService.initInternal(StandardService.java:533)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1059)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:584)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:607)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:304)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
        Caused by: java.net.BindException: Address already in use
                at sun.nio.ch.Net.bind0(Native Method)
                at sun.nio.ch.Net.bind(Net.java:433)
                at sun.nio.ch.Net.bind(Net.java:425)
                at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
                at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
                at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:248)
                at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:222)
                at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1119)
                at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1132)
                at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:557)
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:980)
                ... 13 more
02-Jul-2019 16:10:31.276 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [467] milliseconds
02-Jul-2019 16:10:31.301 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
02-Jul-2019 16:10:31.301 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.20]
02-Jul-2019 16:10:31.318 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/apps/apache-tomcat-9.0.20/webapps/ROOT.war]
02-Jul-2019 16:10:46.158 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
02-Jul-2019 16:10:46.693 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
02-Jul-2019 16:10:46.693 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
02-Jul-2019 16:10:46.700 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/apps/apache-tomcat-9.0.20/webapps/ROOT.war] has finished in [15,382] ms

**Comment by ohaya** [comment]
Oops.  Those (from catalina.out) might've been because I tried to start Tomcat when it was already running.  That was why I tried to reboot the machine earlier.

So probably you can ignore those.  I will cleanup the logs and try a reboot again.

**Comment by ohaya** [comment]
I cleaned out the logs directory (backed up the old files first) and bounced the machine, and I got this in the localhost...log file:

[root@ip-192-168-159-105 logs]# cat localhost.2019-07-02.log
02-Jul-2019 17:25:44.756 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [ocsp-filter]
        java.lang.IllegalArgumentException: could not parse OCSP configuration file xipki/etc/ocsp/ocsp.json
                at org.xipki.ocsp.servlet.OcspServletFilter.init(OcspServletFilter.java:81)
                at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270)
                at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251)
                at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)
                at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4530)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5176)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:713)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:929)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:344)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)
        Caused by: java.nio.file.NoSuchFileException: xipki/etc/ocsp/ocsp.json
                at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
                at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
                at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
                at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
                at java.nio.file.Files.newByteChannel(Files.java:361)
                at java.nio.file.Files.newByteChannel(Files.java:407)
                at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
                at java.nio.file.Files.newInputStream(Files.java:152)
                at org.xipki.ocsp.servlet.OcspConf.readConfFromFile(OcspConf.java:80)
                at org.xipki.ocsp.servlet.OcspServletFilter.init(OcspServletFilter.java:79)
                ... 44 more
02-Jul-2019 17:26:12.113 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
02-Jul-2019 17:26:12.113 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
02-Jul-2019 17:26:12.116 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@785d3dc3')

That ocsp.json file hasn't changed since 6/10/2019, though:

[root@ip-192-168-159-105 ocsp]# ls -ltr
total 12
-rw-r--r--. 1 root root  333 Jun 10 10:58 ocsp.json
drwxr-xr-x. 7 root root 4096 Jun 10 10:58 database
-rw-r--r--. 1 root root 1735 Jun 10 11:06 ocsp-responder.json
[root@ip-192-168-159-105 ocsp]# cd database/
[root@ip-192-168-159-105 database]# ls

**Comment by xipki** [comment]
Tomcat will take the current directory as working directory. So start tomcat In the tomcat root folder, as mentioned in the README.

**Comment by ohaya** [comment]
AHHHH!!  

(a) I remembered that before, and was doing that religiously back then, but (b) this time, I wasn't sure if that was just an old note you had left in your docs and (c) I forgot about it.

I am starting it up again, starting in the /apps/apache-tomcat dir and doing bin/startup.sh. 

I will post back in a bit....

Thanks!

Jim

**Comment by ohaya** [comment]
YES!!  IT IS WORKING AGAIN!!
Now, I have to do some load testing, but I have put some BIG NOTES in our docs about starting Tomcat!

Thanks!

Jim

**Comment by ohaya** [comment]
Closing this issue now.

Thanks again!
