### ISSUE TITLE
Malformed client cert when using Apache reverse proxy

### ISSUE THREAD

**Issue by Sketchy2001** [xipki/xipki#130]
Hi,

I seem to have an issue when proxying the management client.  It works fine when when not proxied.

Versions:
OS: Ubuntu 18.0.4
Tomcat: 9.0.29
XiPKI: 5.3.5
Apache: 2.4.29

XiPKI is still vanilla so using certificates "out of the box"

Regards,
Simon

Apache site config
```
<IfModule mod_ssl.c>
	<VirtualHost _default_:8443>
		ErrorLog 		${APACHE_LOG_DIR}/ca-mgmt-error.log
		CustomLog 		${APACHE_LOG_DIR}/ca-mgmt-access.log combined
		SSLEngine 		on
		SSLCertificateFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/server/tls-server-cert-chained.pem
		SSLCertificateKeyFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/server/tls-server-key.pem
		<Location />
			RequestHeader set SSL_CLIENT_VERIFY "%{SSL_CLIENT_VERIFY}s"
			RequestHeader set SSL_CLIENT_CERT "%{SSL_CLIENT_CERT}s"
			ProxyPass 		ajp://localhost:8009/
			ProxyPassReverse	ajp://localhost:8009/
		</location>
	</VirtualHost>
</IfModule>
```

ca.log output
```
2019-12-02 16:17:35,223 INFO o.x.c.s.CaManagerImpl [main] starting CA system
2019-12-02 16:17:35,223 INFO o.x.c.s.CaManagerImpl [main] ca.masterMode: true
2019-12-02 16:17:35,224 INFO o.x.c.s.CaManagerImpl [main] ca.shardId: 0
2019-12-02 16:17:35,249 INFO c.z.h.HikariDataSource [main] HikariPool-1 - Starting...
2019-12-02 16:17:35,573 INFO c.z.h.HikariDataSource [main] HikariPool-1 - Start completed.
2019-12-02 16:17:35,598 INFO o.x.c.s.CaManagerImpl [main] loaded datasource.ca
2019-12-02 16:17:35,622 INFO o.x.c.s.CaManagerQueryExecutor [main] added system event LOCK
2019-12-02 16:17:35,636 INFO o.x.c.s.CaManagerImpl [main] caAliases: {}
2019-12-02 16:17:35,644 INFO o.x.c.s.CaManagerImpl [main] loaded requestor BY-CA
2019-12-02 16:17:35,645 INFO o.x.c.s.CaManagerImpl [main] loaded requestor BY-USER
2019-12-02 16:17:35,647 INFO o.x.c.s.CaManagerImpl [main] started CA system: no CA is configured
2019-12-02 16:17:35,661 INFO o.x.c.s.CaServletFilter [main] remote management is enabled
2019-12-02 16:19:15,820 INFO o.x.c.s.TlsHelper [ajp-apr-8009-exec-1] set reverseProxyMode to APACHE
2019-12-02 16:28:22,434 ERROR o.x.c.s.HttpMgmtServlet [ajp-apr-8009-exec-3] Throwable thrown, this should not happen!
java.io.IOException: could not parse Certificate
	at org.xipki.ca.servlet.TlsHelper.getTlsClientCert(TlsHelper.java:105) ~[classes/:?]
	at org.xipki.ca.servlet.HttpMgmtServlet.doPost(HttpMgmtServlet.java:105) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
	at org.xipki.ca.servlet.CaServletFilter.doFilter(CaServletFilter.java:225) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.29]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.29]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.29]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [catalina.jar:9.0.29]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.29]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.29]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.29]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.29]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.29]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:396) [tomcat-coyote.jar:9.0.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-coyote.jar:9.0.29]
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:1992) [tomcat-coyote.jar:9.0.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.29]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory$ExCertificateException: parsing issue: malformed PEM data: no header found
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.engineGenerateCertificate(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355) ~[?:?]
	at org.xipki.security.util.X509Util.parseCert(X509Util.java:189) ~[security-5.3.5.jar:?]
	at org.xipki.ca.servlet.TlsHelper.getTlsClientCert(TlsHelper.java:103) ~[classes/:?]
	... 22 more
Caused by: java.io.IOException: malformed PEM data: no header found
	at org.bouncycastle.jcajce.provider.asymmetric.x509.PEMUtil.readPEMObject(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.readPEMCertificate(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.engineGenerateCertificate(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355) ~[?:?]
	at org.xipki.security.util.X509Util.parseCert(X509Util.java:189) ~[security-5.3.5.jar:?]
	at org.xipki.ca.servlet.TlsHelper.getTlsClientCert(TlsHelper.java:103) ~[classes/:?]
	... 22 more
```

**Comment by xipki** [comment]
I added lines to log the TLS certificate. Please replace the ca.war in the folder webapps with the attached ca.war (you get ca.war file atter unzipping the file ca.war.zip).
[ca.war.zip](https://github.com/xipki/xipki/files/3918686/ca.war.zip)

You should still get the same error result, but with more log information. Please upload the ca.log file.

**Comment by Sketchy2001** [comment]
[ca.log](https://github.com/xipki/xipki/files/3918822/ca.log)

**Comment by xipki** [comment]
It seems that the client does not send its certificate to the TLS server (in your case it is the proxy). You need to configure the apache to require client certificate via the option SSLVerifyClient. Please refer to https://httpd.apache.org/docs/2.4/mod/mod_ssl.html for more details related to the configuration of httpd.

**Comment by Sketchy2001** [comment]
Added the following to Apache conf

```
SSLCACertificateFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/ca/tls-ca-cert.pem
SSLVerifyClient		require
```
and error in client changed to 

```
karaf@root()> ca:ca-info 
Error executing command: remote management is not permitted if TLS client certificate is not present
```
Installed latest war file and it works!!
```
karaf@root()> ca:ca-info 
successful CAs:
  -
failed CAs:
  -
inactive CAs:
  -
```
excerpts from ca.log with latest and previous war files.  Note that timestamps are because I re-checked that previous version still gave an error ;o)
```
2019-12-05 12:32:32,106 INFO o.x.c.s.CaServletFilter [main] remote management is enabled
2019-12-05 12:32:51,166 INFO o.x.c.s.TlsHelper [ajp-apr-8009-exec-1] set reverseProxyMode to APACHE
2019-12-05 12:32:51,168 INFO o.x.c.s.TlsHelper [ajp-apr-8009-exec-1] SSL_CLIENT_VERIFY: 'SUCCESS'
2019-12-05 12:32:51,310 INFO o.x.c.s.TlsHelper [ajp-apr-8009-exec-2] SSL_CLIENT_VERIFY: 'SUCCESS'
2019-12-05 12:32:51,325 INFO o.x.c.s.TlsHelper [ajp-apr-8009-exec-3] SSL_CLIENT_VERIFY: 'SUCCESS'
```
```
2019-12-05 12:36:04,231 INFO o.x.c.s.CaServletFilter [Catalina-utility-2] remote management is enabled
2019-12-05 12:36:33,461 INFO o.x.c.s.TlsHelper [ajp-apr-8009-exec-1] set reverseProxyMode to APACHE
```

**Comment by xipki** [comment]
1. That means, the new war file works, is it correct?
2. Could you please share you configuration of apache httpd? I will add it to the README.

**Comment by Sketchy2001** [comment]
1. Correct

2. Apache installed using default Ubuntu package and the following changes were made.
- Enabled ssl, proxy, proxy_ajp and headers modules
- Added and enabled following basic site config
```
<IfModule mod_ssl.c>
	<VirtualHost _default_:8443>
		ErrorLog 		${APACHE_LOG_DIR}/ca-mgmt-error.log
		CustomLog 		${APACHE_LOG_DIR}/ca-mgmt-access.log combined

		SSLEngine 		on
		SSLCertificateFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/server/tls-server-cert-chained.pem
		SSLCertificateKeyFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/server/tls-server-key.pem

		SSLCACertificateFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/ca/tls-ca-cert.pem
		SSLVerifyClient		require

		<Location />
			RequestHeader set SSL_CLIENT_VERIFY "%{SSL_CLIENT_VERIFY}s"
			RequestHeader set SSL_CLIENT_CERT "%{SSL_CLIENT_CERT}s"
			ProxyPass 		ajp://localhost:8009/
			ProxyPassReverse	ajp://localhost:8009/
		</Location>
	</VirtualHost>
</IfModule>
```
For initial config, I have used the default certificates that come with XiPKI.
I guess the ProxyPassReverse is not needed but is there "just in case".
 - Tomcat is configured to run multiple instances via systemd, similar to as described [here](https://gist.github.com/drmalex07/e6e99dad070a78d5dab24ff3ae032ed1).  I can provide more details of that on request.

**Comment by Sketchy2001** [comment]
1. Correct

- Apache installed using default Ubuntu package.
- Enabled ssl, proxy, proxy_ajp and headers modules
- Added and enabled following site config
```
<IfModule mod_ssl.c>
	<VirtualHost _default_:8443>
		ErrorLog 		${APACHE_LOG_DIR}/ca-mgmt-error.log
		CustomLog 		${APACHE_LOG_DIR}/ca-mgmt-access.log combined

		SSLEngine 		on
		SSLCertificateFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/server/tls-server-cert-chained.pem
		SSLCertificateKeyFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/server/tls-server-key.pem

		SSLCACertificateFile	/opt/tomcat/CA/xipki/keycerts/tlskeys/ca/tls-ca-cert.pem
		SSLVerifyClient		require

		<Location />
			RequestHeader set SSL_CLIENT_VERIFY "%{SSL_CLIENT_VERIFY}s"
			RequestHeader set SSL_CLIENT_CERT "%{SSL_CLIENT_CERT}s"
			ProxyPass 		ajp://localhost:8009/
			ProxyPassReverse	ajp://localhost:8009/
		</Location>
	</VirtualHost>
</IfModule>
```
For initial config, I have used the default certificates that come with XiPKI.
I guess the ProxyPassReverse is not needed but is there "just in case".
I also tried adding 
```
SSLOptions +ExportCertData
```
but this did not appear to function as expected.
 - Tomcat configured to run multiple instances via systemd, similar to as described [here](https://gist.github.com/drmalex07/e6e99dad070a78d5dab24ff3ae032ed1).  I can provide more details of that on request.
