### ISSUE TITLE
Problem testing XiPKI OCSPD 

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#153]
Hi,

I am starting test XiPKI OCSPD with one of our XML appliances.  I have configured the appliance to perform 2-way (client-authenticated) SSL and to do OCSP validation using XiPKI OCSPD, and whenever I send a test request into the appliance, XiPKI is throwing errors in the ocsp.log as follows:

```
2020-03-03 04:56:37,444 ERROR o.x.u.LogUtil [http-nio-8080-exec-9] (answer 816), java.lang.IllegalArgumentException: failed to construct object identifier from byte[]: DEF length 60 object truncated by 51
2020-03-03 04:56:37,444 ERROR o.x.u.LogUtil [http-nio-8080-exec-9] Exception
java.lang.IllegalArgumentException: failed to construct object identifier from byte[]: DEF length 60 object truncated by 51
        at org.bouncycastle.asn1.ASN1ObjectIdentifier.getInstance(Unknown Source) ~[bcprov-jdk15on-1.61.jar:1.61.0]
        at org.xipki.ocsp.server.type.ExtendedExtension.getInstance(ExtendedExtension.java:112) ~[ocsp-server-5.3.1.jar:?]
        at org.xipki.ocsp.server.type.OcspRequest.getInstance(OcspRequest.java:148) ~[ocsp-server-5.3.1.jar:?]
        at org.xipki.ocsp.server.OcspServerImpl.checkSignature(OcspServerImpl.java:1160) ~[ocsp-server-5.3.1.jar:?]
        at org.xipki.ocsp.server.OcspServerImpl.answer(OcspServerImpl.java:608) [ocsp-server-5.3.1.jar:?]
        at org.xipki.ocsp.servlet.OcspServlet.doPost(OcspServlet.java:96) [classes/:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at org.xipki.ocsp.servlet.OcspServletFilter.doFilter(OcspServletFilter.java:190) [classes/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.20]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.20]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [catalina.jar:9.0.20]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.20]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.20]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.20]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.20]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.20]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.20]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.20]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.20]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.20]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836) [tomcat-coyote.jar:9.0.20]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839) [tomcat-coyote.jar:9.0.20]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.20]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.20]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

What is causing this problem?

Thanks,
Jim

**Comment by xipki** [comment]
Please upload the OCSP request here or drop me an email.
BTW: Which version of XiPKI do you use?

**Comment by xipki** [comment]
Please upload the OCSP request here or drop me an email.

**Comment by ohaya** [comment]
Hi,

Is there a way to capture the request on the Tomcat/XiPKI side?

Jim

**Comment by ohaya** [comment]
Ok, I sent you a .pcap file captured with tcpdump.

**Comment by xipki** [comment]
This is a bug #154. Your OCSP request contains an extension AcceptableResponses which is not evaluated by the OCSP server.
