### ISSUE TITLE
ca process throwing java.lang.NullPointerException

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#157]
Hi Lijun Liao,

I am using xipki version 5.0.0 with external mariadb in HA mode ..1 master and 2 slave configuration ..

While configuring root CA sometimes i am getting this issue in karaf terminal

``
[[?2004l#################################################################^M
#                     Generate Key and CSR                      #^M
#################################################################^M
saved PKCS#12 keystore to file xipki/ca-setup/keycerts/ztsca.p12^M
saved CSR to file xipki/ca-setup/keycerts/ztsca.csr^M
#################################################################^M
#                       Load ca-conf.json                       #^M
#################################################################^M
^[[31mError executing command: ^[[0m^[[31;1mcould not load configuration xipki/ca-setup/cacert-none/ca-conf.json, error: IOException while sending message to the server: Connection refused (Connection refused)^[[0m^M
^[[37m~^[[0m^[[K
``

when i check the ca tomcat log , i am seeing the below exception

``
07:54:56.799 [http-nio-127.0.0.1-8181-exec-2] ERROR org.xipki.ca.server.RestResponder - Throwable thrown, this should not happen!
java.lang.NullPointerException: null
        at org.xipki.ca.server.RestResponder.service(RestResponder.java:174)
        at org.xipki.ca.servlet.HttpRestServlet.service0(HttpRestServlet.java:83)
        at org.xipki.ca.servlet.HttpRestServlet.doPost(HttpRestServlet.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.xipki.ca.servlet.CaServletFilter.doFilter(CaServletFilter.java:200)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

``
so whenever i am getting this exception, both configuration or certificate fetch is not happening ..
Could you please help me on this ..

[ca-2020-04-07.0.log](https://github.com/xipki/xipki/files/4454557/ca-2020-04-07.0.log)
[karaf.log](https://github.com/xipki/xipki/files/4454566/karaf.log)

Thanks,
Vinoth S

**Comment by xipki** [comment]
Please update to version 5.3.7.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply .. Is there a way to fix this without update ?

Thanks,
Vinoth S

**Comment by xipki** [comment]
The error message "could not load configuration xipki/ca-setup/cacert-none/ca-conf.json ..." in karaf indicates that the server is not still not ready to accept any CA management tasks. You need to start the CA server, wait a few seconds, and then begin to configure CA.

Since the CA is not configured correctly, you get the NullPointerException (NPE). This NPE will be more detailed in the current versio 5.3.7.

**Comment by xipki** [comment]
If you can, please update to the latest release 5.3.7. Many bugs have been fixed after 5.0.0.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply .

Thanks,
Vinoth S
