### ISSUE TITLE
xipki upgrade

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#177]
Hi,

We are planning to upgrade xipki from 5.0.0 to 5.3.7. Planning to use openjdk11 and Tomcat 9.0.37 

https://github.com/xipki/xipki/issues/123 has the upgrade DB alteration commands from 5.0.0 to 5.3.4. 

Please mention if there are any additional schema updates for 5.3.7 if you are aware beforehand.

Thanks,
Meghana

**Comment by xipki** [comment]
Hi Meghana,

that's all as in #123.

I just released v5.3.8. Please use this one.

BR
Lijun

**Comment by meghana-svg** [comment]
Hi,
We are getting following issues with 5.3.8. This configuration was working in 5.0.0
1. Running of setup shows following error
a. Command line shows 
#################################################################
#                       Load ca-conf.json                       #
#################################################################
loaded configuration xipki/ca-setup/cacert-none/ca-conf.json
saved certificate of root CA ztsca to xipki/ca-setup/keycerts/ca-ztsca.crt
Error executing command: xipki/ca-setup/keycerts/ca-ztsca.der does not exist
karaf@root()>
b. Karaf log shows exception
Exception caught while executing command
org.xipki.shell.IllegalCmdParamException: xipki/ca-setup/keycerts/ca-ztsca.der does not exist
	at org.xipki.shell.Actions$MoveFile.execute0(Actions.java:386) ~[?:?]
	at org.xipki.shell.XiAction.execute(XiAction.java:64) ~[?:?]
	
2. CSR is failing with the error. 
2020-07-15 10:47:16,985 WARN o.x.u.LogUtil [http-nio-127.0.0.1-8181-exec-9] (service 575) generate certificate, OperationException: code=BAD_CERT_TEMPLATE, message=error code: BAD_CERT_TEMPLATE, error message: BadCertTemplateException: invalid subject 2.5.4.3 (cn) 'caserverservice.ca.svc.cluster.local' against regex ':FQDN', org.xipki.ca.server.X509Ca$OperationExceptionWithIndex: error code: BAD_CERT_TEMPLATE, error message: error code: BAD_CERT_TEMPLATE, error message: BadCertTemplateException: invalid subject 2.5.4.3 (cn) 'caserverservice.ca.svc.cluster.local' against regex ':FQDN'

CSR syntax is 
curl --insecure --globoff --user user:passwd --header "Content-Type: application/pkcs10" --data-binary "@output/certs/cert.csr" --output output/certs/cert.der http://localhost:8181/ca/rest/ca/enroll-cert?profile=tls
3. We are not deploying the OCSP.war as we are not using OCSP
Attaching csr, Catalina.out, ca-log, access-log and [karaf.log[]
[access.log](https://github.com/xipki/xipki/files/4925302/access.log)
[karaf.log](https://github.com/xipki/xipki/files/4925303/karaf.log)
[ca.log](https://github.com/xipki/xipki/files/4925304/ca.log)
[cert.csr.txt](https://github.com/xipki/xipki/files/4925349/cert.csr.txt)
[catalina.out.log](https://github.com/xipki/xipki/files/4925352/catalina.out.log)


Thanks,
Meghana

**Comment by xipki** [comment]
Please remove the line `"regex":":FQDN",` in the file `certprofile-tls.json` and retry.

**Comment by subyphilip** [comment]
We have brought up the system with the patch, we are getting two issues
1. First time, start failed with following ca-log
2020-07-16 10:14:57,681 INFO o.x.c.s.CaManagerImpl [main] loaded datasource.ca
2020-07-16 10:14:57,727 ERROR o.x.u.LogUtil [main] (startCaSystem0 633), org.xipki.ca.api.mgmt.CaMgmtException: BadSqlGrammar - SQL [SELECT EVENT_TIME,EVENT_OWNER FROM SYSTEM_EVENT WHERE NAME=? LIMIT 1]; (conn=32) Table 'ca.SYSTEM_EVENT' doesn't exist
2020-07-16 10:14:57,729 ERROR o.x.c.s.CaManagerImpl [main] could not start CA system

My understanding is during fresh install, tomcat should be able to deploy ca.war and CA should start with out certificate. At that point of DB will be empty.

Another issue, while running setup-ec-p12 script, we see the following error
 Error executing command: xipki/ca-setup/keycerts/ca-ztsca.der does not exist.
Can we ignore

**Comment by xipki** [comment]
Hi Meghana,

As I understand, you plan to upgrade the CA software using the existing database. In this case you do not need to setup the CA using setup-*.script. The required steps are:
  1. Backup the database (so that the data will not be lost)
  2. Change the database schema as described above.
  3. Install the CA software (as described in the README after unpacking ca-war-*.zip)

**Comment by subyphilip** [comment]
Hi Lijun,
We are supporting both scenarios, in existing setups, we are planning upgrade. But we also have Fresh Install in some labs, where we will use setup-* script.

**Comment by xipki** [comment]
For the fresh install, just follow the project's README.md.

Related the problems mentioned above:
1. You need to create and initialize the database.
2.  You need to use the script in the folder `cacert-none`. You seem to use the folder `cacert-present`.

**Comment by subyphilip** [comment]
Thanks Lijun. Fresh install scenario is working barring a warning. Now We are checking the upgrade.   As you have advised, we backed up the database ,changed the schema and installed CA. But the CA installation is failing with exception in ca.log.
2020-07-18 15:15:01,565 ERROR o.x.u.LogUtil [main] (startCaSystem0 633), java.lang.IllegalArgumentException: Requestor name could not be by-ca
2020-07-18 15:15:01,566 ERROR o.x.u.LogUtil [main] Exception
java.lang.IllegalArgumentException: Requestor name could not be by-ca
        at org.xipki.ca.api.mgmt.MgmtEntry$Requestor.<init>(MgmtEntry.java:1335) ~[ca-api-5.3.8.jar:?]
        at org.xipki.ca.server.CaManagerQueryExecutor.createRequestor(CaManagerQueryExecutor.java:449) ~[ca-server-5.3.8.jar:?]
        at org.xipki.ca.server.CaManagerImpl.initRequestors(CaManagerImpl.java:939) ~[ca-server-5.3.8.jar:?]
        at org.xipki.ca.server.CaManagerImpl.init(CaManagerImpl.java:463) ~[ca-server-5.3.8.jar:?]
        at org.xipki.ca.server.CaManagerImpl.startCaSystem0(CaManagerImpl.java:631) [ca-server-5.3.8.jar:?]
        at org.xipki.ca.server.CaManagerImpl.startCaSystem(CaManagerImpl.java:608) [ca-server-5.3.8.jar:?]
        at org.xipki.ca.servlet.CaServletFilter.init(CaServletFilter.java:139) [classes/:?]
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270) [catalina.jar:9.0.37]
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251) [catalina.jar:9.0.37]
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102) [catalina.jar:9.0.37]
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4528) [catalina.jar:9.0.37]
2020-07-18 15:15:01,606 ERROR o.x.c.s.CaManagerImpl [main] could not start CA system

I couldn't backup the entire log file.

**Comment by xipki** [comment]
Hi Meghana,

sorry for the inconvenience. After v5.0.0, requestor names will be saved in database in lowercase. But in your version (v5.0.0), they seem to be saved as given. I will fixed this incompatibility in the next release (v5.3.8).

For your case, please change all requestor name to lowercase in the table REQUESTOR in CA's database.

**Comment by xipki** [comment]
Related to #179.

**Comment by subyphilip** [comment]
Upgrade worked with above change. Thanks Lijun. 
We are observing an issue in fresh install with new certificate, client- server communication is failing. The error thrown is
    140510827429192:error:14094413:SSL routines:ssl3_read_bytes:sslv3 alert unsupported certificate:ssl/record/rec_layer_s3.c:1543:SSL alert number 43
This issue occurs when certificate does not have client authentication. We examined certificates generated for 5.0 and 5.3.8.  5.3.8 is not having client authentication.  
5.3.8
 X509v3 Extended Key Usage:
                TLS Web Server Authentication
5.0.0
X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication


tls-c.json has extendedkeyusage:true by default, tls.json has client authentication extendedkeyusage set to false, but even setting to true didn't change contents of certificate.
Attaching the cert.pem (original and described) for both 5.0 and 5.3.8
Could you pls check this

**Comment by xipki** [comment]
In the file `tls.json`, the following block controls the extension ExtendedKeyUsage:
```
	},{
		"type":{
			"oid":"2.5.29.37",
			"description":"extendedKeyUsage"
		},
		"critical":false,
		"required":true,
		"permittedInRequest":true,
		"extendedKeyUsage":{
			"usages":[{
				"required":true,
				"oid":"1.3.6.1.5.5.7.3.1",
				"description":"TLS WWW server authentication"
			},{
				"required":false,
				"oid":"1.3.6.1.5.5.7.3.2",
				"description":"TLS WWW client authentication"
			}]
		}
	}
```
As defined above, the usage "server authentication" will be included, but the usage "client authentication" will be included only if this usage is contained in the request.

If you do not have the control over request, you need to change the "required" of "client authentication", in the file tls.json, from false to true. Then update the database via karaf command:
```
profile-up --name tls --conf-file xipki/ca-setup/certprofile/certprofile-tls.json 
```

**Comment by xipki** [comment]
Does the problem still exist? If not, I will close this issue.

**Comment by meghana-svg** [comment]
Hi Lijun,

We are testing few more scenarios, will update in couple of days.

Thanks,
Meghana

**Comment by meghana-svg** [comment]
Hi Lijun,

Thanks for your support. Upgrade works fine now.
Closing the ticket.

Thanks,
Meghana

**Comment by meghana-svg** [comment]
Hi Lijun,

Thanks for your support. Upgrade works fine now.
Closing the ticket.

Thanks,
Meghana
