### ISSUE TITLE
xipki upgrade from 5.3.8 to 5.3.10

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#190]
Hi Lijun,

We are trying to upgrade xipki from 5.3.8 to 5.3.10 and we are facing the below issue which was working fine in 5.3.8 release.

2020.10.12-04:49:46.398 http-nio-127.0.0.1-8181-exec-2 ERROR: X509Ca.generateCerts()      FAILED createGrantedCertTemplate: CA=ztsca, profile=tls, subject='CN=generic,O=nokia
[ca.log](https://github.com/xipki/xipki/files/5364754/ca.log)
,C=IN'
2020.10.12-04:49:46.399 http-nio-127.0.0.1-8181-exec-2 WARN: LogUtil.warn() (service 578) generate certificate, OperationException: code=BAD_CERT_TEMPLATE, message=error code: BAD_CERT_TEMPLATE, error message: BadCertTemplateException: invalid subject 2.5.4.3 (cn) 'generic' against regex ':FQDN', org.xipki.ca.server.X509Ca$OperationExceptionWithIndex: error code: BAD_CERT_TEMPLATE, error message: error code: BAD_CERT_TEMPLATE, error message: BadCertTemplateException: invalid subject 2.5.4.3 (cn) 'generic' against regex ':FQDN'

we are using the subject as CN=generic.

Can you please suggest any workaround or do we need to make any changes in our system.

Attaching the ca.log for reference.

Thanks,
Meghana

**Comment by xipki** [comment]
The certificate profile requires that the CN is a FQDN (like example.com), but the given one 'generic' is NOT a valid FQDN..
For solution please refer to the comment in https://github.com/xipki/xipki/issues/177.

**Comment by meghana-svg** [comment]
Hi Lijun,

Thanks for the quick response.

We are facing another issue while configuring ca with xipki 5.3.10, this issue was observed in couple of deployments,

Below is the observed error,

2020.10.22-08:22:04.034 https-openssl-nio-8443-exec-6 INFO: CaManagerImpl.removeCertprofile() removed profile 'rootca'
2020.10.22-08:22:28.756 http-nio-127.0.0.1-8181-exec-7 ERROR: RestResponder.service() Throwable thrown, this should not happen!: java.lang.NullPointerException: ident may not be null
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at org.xipki.util.Args.notNull(Args.java:144)
        at org.xipki.ca.api.mgmt.RequestorInfo$ByUserRequestorInfo.<init>(RequestorInfo.java:182)
        at org.xipki.ca.server.CaManagerImpl.createByUserRequestor(CaManagerImpl.java:1195)
        at org.xipki.ca.server.X509Ca.getByUserRequestor(X509Ca.java:587)
        at org.xipki.ca.server.RestResponder.service(RestResponder.java:299)
        at org.xipki.ca.servlet.HttpRestServlet.service0(HttpRestServlet.java:92)
        at org.xipki.ca.servlet.HttpRestServlet.doGet(HttpRestServlet.java:72)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.xipki.ca.servlet.CaServletFilter.doFilter(CaServletFilter.java:213)
2020.10.22-08:23:15.022 main INFO: CaManagerImpl.init() associate datasource ca to the file etc/ca/database/ca-db.properties
2020.10.22-08:23:15.041 main INFO: HikariDataSource.<init>() HikariPool-1 - Starting...
2020.10.22-08:23:16.244 main ERROR: HikariPool.throwPoolInitializationException() HikariPool-1 - Exception during pool initialization.: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=ca-mariadb)(port=3306)(type=master) : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
        at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:277)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.xipki.datasource.DataSourceWrapper.createDataSource(DataSourceWrapper.java:1196)
        at org.xipki.datasource.DataSourceFactory.createDataSource(DataSourceFactory.java:150)
        at org.xipki.datasource.DataSourceFactory.createDataSource(DataSourceFactory.java:59)
        at org.xipki.ca.server.CaManagerImpl.loadDatasource(CaManagerImpl.java:497)
        at org.xipki.ca.server.CaManagerImpl.init(CaManagerImpl.java:452)
        at org.xipki.ca.server.CaManagerImpl.startCaSystem0(CaManagerImpl.java:662)
        at org.xipki.ca.server.CaManagerImpl.startCaSystem(CaManagerImpl.java:639)

Can you please suggest any workaround or any other way forword.

Attaching the ca logs and configuration logs for reference.

Thanks,
Meghana
 	

[ca.log](https://github.com/xipki/xipki/files/5428301/ca.log)
[configuration.log](https://github.com/xipki/xipki/files/5428303/configuration.log)

**Comment by xipki** [comment]
The first exception `ERROR: RestResponder.service()`was thrown since you accessed to the CA via the REST API while the setup of CA was not finished.

The second exception `HikariPool-1 - Exception during pool initialization` was thrown since HikariPool could not establish the connection with database server due to the reason `socket was closed by server`. I am not familiar with database connection. You may refer to [HikariCP](https://github.com/brettwooldridge/HikariCP) or the mariadb discussion group for help.

**Comment by xipki** [comment]
would not fix.
