### ISSUE TITLE
Exception seen in catalina.out file

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#214]
Hi Lijun,

We are using xipki version 5.3.10. And we hit the below error in the catalina.out file

29-Jun-2021 08:09:38.814 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.39]
29-Jun-2021 08:09:38.896 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/ca.war]
29-Jun-2021 08:09:39.298 SEVERE [main] org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource Unable to process web resource [/WEB-INF/classes/org/xipki/ca/servlet/HttpMgmtServlet$1.class] for annotations
        java.io.EOFException
                at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
                at org.apache.tomcat.util.bcel.classfile.ClassParser.readID(ClassParser.java:199)
                at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:78)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2351)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2250)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2244)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2244)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2244)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2244)
                at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1397)
      at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
29-Jun-2021 08:09:39.497 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat/webapps/ca.war] has finished in [601] ms
29-Jun-2021 08:09:39.498 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/ocsp.war]
 
Java version used:
causer@caserver-0 /]$ java --version
openjdk 11.0.8 2020-07-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode, sharing)

Tomcat version used: 9.0.46

Due to this exception xipki is unable to create the ca log file in the /opt/tomcat/logs directory.

Could you please suggest some WA for this exception if any?

Attaching the catalina.out file for reference.
[catalina.txt](https://github.com/xipki/xipki/files/6732169/catalina.txt)

Thanks,
Meghana

**Comment by xipki** [comment]
Please remove the sub-folder `ca`, then restart the tomcat.

**Comment by meghana-svg** [comment]
Thank you for your quick response.
