### ISSUE TITLE
OCSP responder: no such algorithm

### ISSUE THREAD

**Issue by kir-b** [xipki/xipki#217]
Hi,
strange problem occurs when i run ocsp. Could you help me with it?
```2021.07.26-19:27:00.165 main INFO: XipkiBaseDir.init() working dir is /var/lib/jetty
2021.07.26-19:27:00.167 main INFO: XipkiBaseDir.init() use default basedir '/var/lib/jetty/xipki', can be specified via the property 'XIPKI_BASE'
2021.07.26-19:27:00.243 main INFO: OcspServletFilter.init() logReqResp: false
2021.07.26-19:27:00.389 main INFO: Securities.init() add BouncyCastleProvider
2021.07.26-19:27:00.497 main INFO: SignerFactoryRegisterImpl.registFactory() added SignerFactory binding for org.xipki.security.pkcs12.P12SignerFactory@31e3250d
2021.07.26-19:27:00.498 main INFO: P11ModuleFactoryRegisterImpl.registFactory() added P11ModuleFactory binding for org.xipki.security.pkcs11.iaik.IaikP11ModuleFactory@24fb6a80
2021.07.26-19:27:00.498 main INFO: P11ModuleFactoryRegisterImpl.registFactory() added P11ModuleFactory binding for org.xipki.security.pkcs11.emulator.EmulatorP11ModuleFactory@48c35007
2021.07.26-19:27:00.498 main INFO: P11ModuleFactoryRegisterImpl.registFactory() added P11ModuleFactory binding for org.xipki.security.pkcs11.proxy.ProxyP11ModuleFactory@72a85671
2021.07.26-19:27:00.520 main INFO: SignerFactoryRegisterImpl.registFactory() added SignerFactory binding for org.xipki.security.pkcs11.P11SignerFactory@4215838f
2021.07.26-19:27:00.543 main INFO: OcspServerImpl.<init>() XiPKI OCSP Responder version 5.3.13
2021.07.26-19:27:00.544 main INFO: OcspServerImpl.init() starting OCSPResponder server ...
2021.07.26-19:27:00.675 main ERROR: OcspServerImpl.init() could not start OCSP responder: org.xipki.util.InvalidConfException: org.xipki.security.XiSecurityException: no such algorithm
	at org.xipki.ocsp.server.OcspServerUtil.initSigner(OcspServerUtil.java:104)
	at org.xipki.ocsp.server.OcspServerImpl.init0(OcspServerImpl.java:420)
	at org.xipki.ocsp.server.OcspServerImpl.init(OcspServerImpl.java:231)
	at org.xipki.ocsp.server.OcspServerImpl.init(OcspServerImpl.java:217)
	at org.xipki.ocsp.servlet.OcspServletFilter.init(OcspServletFilter.java:96)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:140)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:517)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:157)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:442)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:785)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:754)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:146)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1907)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857)
Caused by: org.xipki.util.ObjectCreationException: org.xipki.security.XiSecurityException: no such algorithm
	at org.xipki.security.pkcs12.P12SignerFactory.newSigner(P12SignerFactory.java:167)
	at org.xipki.security.SignerFactoryRegisterImpl.newSigner(SignerFactoryRegisterImpl.java:91)
	at org.xipki.security.SecurityFactoryImpl.createSigner(SecurityFactoryImpl.java:92)
	at org.xipki.ocsp.server.OcspServerUtil.initSigner(OcspServerUtil.java:99)
	... 43 more
2021.07.26-19:27:00.675 main ERROR: LogUtil.error() (init 98) could not start OCSP server, org.xipki.util.InvalidConfException: org.xipki.security.XiSecurityException: no such algorithm
2021.07.26-19:27:00.675 main DEBUG: LogUtil.error() could not start OCSP server: org.xipki.util.InvalidConfException: org.xipki.security.XiSecurityException: no such algorithm
	at org.xipki.ocsp.server.OcspServerUtil.initSigner(OcspServerUtil.java:104)
	at org.xipki.ocsp.server.OcspServerImpl.init0(OcspServerImpl.java:420)
	at org.xipki.ocsp.server.OcspServerImpl.init(OcspServerImpl.java:231)
	at org.xipki.ocsp.server.OcspServerImpl.init(OcspServerImpl.java:217)
	at org.xipki.ocsp.servlet.OcspServletFilter.init(OcspServletFilter.java:96)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:140)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:517)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:157)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:442)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:785)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:754)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:146)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1907)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857)
Caused by: org.xipki.util.ObjectCreationException: org.xipki.security.XiSecurityException: no such algorithm
	at org.xipki.security.pkcs12.P12SignerFactory.newSigner(P12SignerFactory.java:167)
	at org.xipki.security.SignerFactoryRegisterImpl.newSigner(SignerFactoryRegisterImpl.java:91)
	at org.xipki.security.SecurityFactoryImpl.createSigner(SecurityFactoryImpl.java:92)
	at org.xipki.ocsp.server.OcspServerUtil.initSigner(OcspServerUtil.java:99)
	... 43 more
2021.07.26-19:27:00.679 main INFO: OcspServletFilter.init() remote management is disabled
```

**Comment by xipki** [comment]
Please upload your configuration file of OCSP (without any password).

**Comment by kir-b** [comment]
Hi @xipki 
Thanks for quick response.
I have found the bug. Default signer algorithm was SHA256withECDSA (default), but I use RSA certificate.
