### ISSUE TITLE
Quickstart: Fails with BC error: can't find ISISMTTObjectIdentifiers

### ISSUE THREAD

**Issue by nynymike** [xipki/xipki#220]
On the OCSP responder, I am getting a message like this:

```
2021-07-30 17:00:16.467:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@696da30b{XiPKI OCSP Web Application,/ocsp,file:///tmp/jetty-0_0_0_0-8080-ocsp_war-_ocsp-any-3189569486399442767/webapp/,UNAVAILABLE}{/opt/xipki/jetty/webapps/ocsp.war}
java.lang.NoClassDefFoundError: org/bouncycastle/asn1/isismtt/ISISMTTObjectIdentifiers
	at org.xipki.ocsp.server.type.OID.<clinit>(OID.java:41)
	at org.xipki.ocsp.server.OcspServerImpl.<clinit>(OcspServerImpl.java:166)
	at org.xipki.ocsp.servlet.OcspServletFilter.init(OcspServletFilter.java:91)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:140)

```

Note: I do have BounceyCastle in my `lib/ext` folder:

```
$ ls lib/ext
bcpkix-jdk15on-169.jar  bcprov-jdk15on-169.jar   mysql-connector-java-8.0.26.jar

```

And I see the class there:

```
$ jar tvf bcprov-jdk15on-169.jar | grep ISISMTTObjectIdentifiers
  1689 Mon Jun 07 07:04:58 CDT 2021 org/bouncycastle/internal/asn1/isismtt/ISISMTTObjectIdentifiers.class

```

Note: I am running jetty with `{JETTY_HOME}/bin/jetty.sh start`. I added `JETTY_HOME` to my `.profile`.  

Also, I suggest on `xipki/etc/ocsp/database/ca-db.properties` that you make the default value for `dataSource.databaseName` = `ocsp` rather then `ca` ... lest the db init script drops the ca database.

**Comment by xipki** [comment]
Related to the configuration of ca-db.properties in OCSP responder. As in the README, the user only needs to init the ocsp-crl-db.properties and ocsp-cache-db.properties, if related. But not ca-db.properties. Setting it to CA's database simplifying the setup of CA and covers the most user cases.

**Comment by nynymike** [comment]
Ok, thanks.
