### ISSUE TITLE
How to create a "right" ocsp server cert and use it?

### ISSUE THREAD

**Issue by jeschero** [xipki/xipki#232]
**Problem**

Change the  ocsp web address for the ocsp server cert and the Issuer.

**Procedure**
Create the ca and ocsp server on the basis of the README.md and start the service

Use the [myownca.txt](https://github.com/xipki/xipki/files/7721970/myownca.txt) and [template.ca-conf.txt](https://github.com/xipki/xipki/files/7721971/template.ca-conf.txt) over the cli to create the new ca. 

Restart the xipki, if not i get with `openssl ocsp  ...` the error `Responder Error: malformedrequest (1)`

Create with [rest.txt](https://github.com/xipki/xipki/files/7721995/rest.txt) over REST a cert. I get the error `139635004503424:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:92:Verify error:unable to get local issuer certificate`. 

I can see now the ocsp server cert:
```
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = DE, O = xipki, CN = OCSP1
    Produced At: Oct  2 09:29:21 2021 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: EC08092070D0531C8785F210BD81D9200F99F11A
      Issuer Key Hash: EC24B6F3448A12C2668900B20F985409190D04D0
      Serial Number: 263C92BB8A3EF3E1FB602385207CEC004AF0C878
    Cert Status: revoked
    Revocation Time: Oct  2 09:18:50 2021 GMT
    Revocation Reason: keyCompromise (0x1)
    This Update: Oct  2 09:29:21 2021 GMT

    Response Extensions:
        OCSP Nonce: 
            0410E39BC936034B0342C2A823B4567D04D7
    Signature Algorithm: sha256WithRSAEncryption
         7b:4c:c0:57:11:45:19:ca:e4:d5:26:90:00:8e:05:fa:7a:f4:
         77:5c:60:f1:6e:84:e4:72:28:2b:0f:35:31:ec:a8:ae:a8:63:
         38:ef:93:ab:c6:52:17:20:b0:bf:89:52:8c:bd:24:0e:70:0b:
         e1:5e:1e:83:bb:44:dc:8e:29:42:8a:1f:0d:10:e8:d2:74:7f:
         13:ea:ce:91:5e:39:46:3c:49:54:16:d2:15:5a:d5:fc:a1:3a:
         a9:ef:fc:01:56:87:fd:9f:74:6f:25:90:8a:4f:6c:22:8c:4f:
         da:23:02:61:96:cf:c7:d2:79:fe:c2:c1:b7:e5:08:fe:e2:13:
         ef:b4:2c:36:49:3e:68:aa:93:9c:c5:91:34:a2:cf:47:3d:6a:
         67:f9:63:de:27:34:42:ad:6c:46:59:90:4c:0b:48:f0:71:59:
         f3:62:c6:94:d2:61:ed:16:e5:15:c7:a8:84:4f:80:76:00:3c:
         19:2e:f6:da:b9:17:03:e1:f1:79:49:ef:16:5c:61:5c:a9:d1:
         e0:82:fe:80:1c:ad:99:18:ad:e7:47:00:22:46:83:ea:9b:d8:
         56:87:1d:81:f1:61:0d:e0:5a:f9:59:39:c3:b7:6b:99:62:2d:
         e5:0e:91:45:50:bb:55:be:d2:45:37:fd:e9:95:fa:89:9d:a4:
         48:02:48:9a
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 644222008542029927 (0x8f0bc80e7a2e867)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=DE, O=xipki, CN=myca1
        Validity
            Not Before: Oct 18 05:55:48 2018 GMT
            Not After : Oct 18 05:55:47 2023 GMT
        Subject: C=DE, O=xipki, CN=OCSP1
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ac:88:25:56:13:0b:af:fc:06:f8:53:a2:86:40:
                    66:56:8b:7f:35:b3:8a:a7:f4:32:31:39:c9:97:28:
                    48:d0:94:c2:3f:56:ce:9b:68:83:d1:30:eb:7c:6d:
                    36:8a:8e:f1:7c:d8:9f:fe:59:b3:54:4b:fa:79:6b:
                    ab:74:0d:c4:74:31:19:72:fa:a7:7e:08:27:1b:fc:
                    5d:3a:0f:85:77:8a:3d:5f:fa:71:60:67:9c:64:79:
                    33:11:0d:0e:e4:fe:ae:c9:d5:eb:bc:77:ec:97:7f:
                    a1:3e:ec:e0:64:63:7a:79:b0:ed:6b:0f:8e:33:9a:
                    03:bf:8d:3f:01:a9:e9:be:bc:7f:4c:93:96:41:90:
                    b6:c7:9f:65:32:74:07:5c:59:57:a0:e1:cf:fc:15:
                    98:8f:dd:80:e0:62:a3:2e:96:6c:0a:33:68:ac:22:
                    f7:34:57:29:d6:1c:ba:f7:fb:98:de:fa:76:9d:ab:
                    2f:a9:ce:70:80:b9:72:66:9c:19:8f:27:e6:fa:1d:
                    da:5a:50:f3:00:53:0c:5b:30:26:84:e5:84:8f:e6:
                    89:54:f6:ba:96:56:93:86:ab:44:5c:c6:c6:17:e5:
                    82:c7:24:bf:66:e2:33:90:4d:0e:48:46:de:23:a7:
                    69:cc:69:52:32:27:88:ea:f8:60:d0:66:52:d4:d6:
                    aa:23
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            Authority Information Access: 
                OCSP - URI:http://localhost:8080/ocsp/responder1

            X509v3 Authority Key Identifier: 
                keyid:DC:CC:C5:70:F4:2E:AC:F4:0F:D6:AC:DA:A9:BE:96:40:D7:FB:86:87
                DirName:/C=DE/O=xipki/CN=myca1
                serial:01

            X509v3 Subject Key Identifier: 
                FF:03:A9:27:9C:5E:54:6F:80:3E:16:E9:56:44:94:9C:31:D3:13:A3
            X509v3 Key Usage: critical
                Non Repudiation
            X509v3 Extended Key Usage: 
                OCSP Signing
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:94:ba:bd:e8:df:45:d5:e2:f6:f9:18:30:ed:
         2e:60:f0:66:1f:c2:48:ad:57:97:d8:ee:53:cd:99:5b:8c:a5:
         be:02:21:00:8a:68:e1:85:24:48:9b:72:18:fa:e4:e8:2f:fe:
         50:ef:ed:2c:4a:5b:3c:e0:78:d3:f8:3d:8d:8d:de:50:dd:89
-----BEGIN CERTIFICATE-----
MIIDDDCCArGgAwIBAgIICPC8gOei6GcwCgYIKoZIzj0EAwIwLTELMAkGA1UEBhMC
REUxDjAMBgNVBAoMBXhpcGtpMQ4wDAYDVQQDDAVteWNhMTAeFw0xODEwMTgwNTU1
NDhaFw0yMzEwMTgwNTU1NDdaMC0xCzAJBgNVBAYTAkRFMQ4wDAYDVQQKDAV4aXBr
aTEOMAwGA1UEAwwFT0NTUDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQCsiCVWEwuv/Ab4U6KGQGZWi381s4qn9DIxOcmXKEjQlMI/Vs6baIPRMOt8bTaK
jvF82J/+WbNUS/p5a6t0DcR0MRly+qd+CCcb/F06D4V3ij1f+nFgZ5xkeTMRDQ7k
/q7J1eu8d+yXf6E+7OBkY3p5sO1rD44zmgO/jT8Bqem+vH9Mk5ZBkLbHn2UydAdc
WVeg4c/8FZiP3YDgYqMulmwKM2isIvc0VynWHLr3+5je+nadqy+pznCAuXJmnBmP
J+b6HdpaUPMAUwxbMCaE5YSP5olU9rqWVpOGq0RcxsYX5YLHJL9m4jOQTQ5IRt4j
p2nMaVIyJ4jq+GDQZlLU1qojAgMBAAGjge8wgewwDAYDVR0TAQH/BAIwADBBBggr
BgEFBQcBAQQ1MDMwMQYIKwYBBQUHMAGGJWh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9v
Y3NwL3Jlc3BvbmRlcjEwVQYDVR0jBE4wTIAU3MzFcPQurPQP1qzaqb6WQNf7hoeh
MaQvMC0xCzAJBgNVBAYTAkRFMQ4wDAYDVQQKDAV4aXBraTEOMAwGA1UEAwwFbXlj
YTGCAQEwHQYDVR0OBBYEFP8DqSecXlRvgD4W6VZElJwx0xOjMA4GA1UdDwEB/wQE
AwIGQDATBgNVHSUEDDAKBggrBgEFBQcDCTAKBggqhkjOPQQDAgNJADBGAiEAlLq9
6N9F1eL2+Rgw7S5g8GYfwkitV5fY7lPNmVuMpb4CIQCKaOGFJEibchj65Ogv/lDv
7SxKWzzgeNP4PY2N3lDdiQ==
-----END CERTIFICATE-----

**Comment by xipki** [comment]
What is the xipki version? Do you need OCSP server?

**Comment by xipki** [comment]
Seems to be inactive. Please re-open this issue if problem still exists.

**Comment by jeschero** [comment]
> What is the xipki version?
I used the version v5.3.13, need i upgrade first to the new version to configure it?

> Do you need OCSP server?
If it possible. The OCSP server is on of the major point why i will use xipki

**Comment by xipki** [comment]
In the master branch I optimized the installation steps for CA and OCSP steps. Please build the project, and install the CA, the OCSP responder as described in the project's README.

Then setup the CA and OCSP server as follows (the following script use the ECDSA signature and PKCS#12 key, you may replace `ec` with `rsa` to use RSA signature, and `p12` with `p11` to use PKCS#11 key):
1. Start tomcat
2. source xipki/cacert-none/setup-ec-p12.script
3. source xipki/setup-ocsp.script (at the end of this step you need to copy a file to ocsp folder and restart the tomcat).

Now you can test the ocsp responder using the script `./rest.sh ocsp`.

**Comment by jeschero** [comment]
sorry for my late feedback, but i only now found time to install the new version.
 
You write that I should run "source xipki/ca-setup/setup-ocsp-p12.script" in step three, but the file does not exist. I only see the file "setup-scep.script". And which file i need to copy after i executed the script?

**Comment by xipki** [comment]
You need to build it from source code (the last branch).

**Comment by jeschero** [comment]
I started the build from the master branch but get some errors:

```
$ mvn validate
# every is fine
$ mvn compile
...
[INFO] Reactor Summary:
[INFO] 
[INFO] XiPKI :: xipki-parent 5.3.15-SNAPSHOT .............. SUCCESS [  0.995 s]
[INFO] XiPKI :: util ...................................... SUCCESS [  3.797 s]
[INFO] XiPKI :: audit ..................................... SUCCESS [  0.398 s]
[INFO] XiPKI :: password .................................. SUCCESS [  0.454 s]
[INFO] XiPKI :: datasource ................................ SUCCESS [  0.714 s]
[INFO] XiPKI :: dbtool .................................... SUCCESS [  0.266 s]
[INFO] XiPKI :: security .................................. SUCCESS [  3.876 s]
[INFO] XiPKI :: security-extra ............................ SUCCESS [  1.376 s]
[INFO] XiPKI :: p11proxy-servlet .......................... SUCCESS [  0.331 s]
[INFO] XiPKI :: cmpclient ................................. SUCCESS [  0.770 s]
[INFO] XiPKI :: scep-client ............................... SUCCESS [  0.583 s]
[INFO] XiPKI :: ocsp-client ............................... SUCCESS [  0.244 s]
[INFO] XiPKI :: ca-api .................................... SUCCESS [  1.605 s]
[INFO] XiPKI :: ca-server ................................. SUCCESS [  2.229 s]
[INFO] XiPKI :: certprofile-xijson ........................ SUCCESS [  0.840 s]
[INFO] XiPKI :: ca-servlet ................................ SUCCESS [  0.518 s]
[INFO] XiPKI :: ca-mgmt-client ............................ SUCCESS [  1.087 s]
[INFO] XiPKI :: ocsp-api .................................. SUCCESS [  0.214 s]
[INFO] XiPKI :: ocsp-server ............................... SUCCESS [  0.915 s]
[INFO] XiPKI :: ocsp-servlet .............................. SUCCESS [  0.262 s]
[INFO] XiPKI :: ocsp-mgmt-client .......................... SUCCESS [  0.183 s]
[INFO] XiPKI :: shells .................................... SUCCESS [  0.012 s]
[INFO] XiPKI :: shell-base ................................ SUCCESS [  0.285 s]
[INFO] XiPKI :: security-shell ............................ SUCCESS [  0.458 s]
[INFO] XiPKI :: cmpclient-shell ........................... SUCCESS [  0.361 s]
[INFO] XiPKI :: ocsp-client-shell ......................... SUCCESS [  0.242 s]
[INFO] XiPKI :: scep-client-shell ......................... SUCCESS [  0.261 s]
[INFO] XiPKI :: ca-mgmt-shell ............................. SUCCESS [  0.689 s]
[INFO] XiPKI :: ocsp-mgmt-shell ........................... SUCCESS [  0.148 s]
[INFO] XiPKI :: dbtool-shell .............................. SUCCESS [  0.110 s]
[INFO] XiPKI :: qa ........................................ SUCCESS [  1.312 s]
[INFO] XiPKI :: qa-shell .................................. SUCCESS [  0.690 s]
[INFO] XiPKI :: examples .................................. SUCCESS [  0.011 s]
[INFO] XiPKI :: example :: certprofile-example ............ SUCCESS [  0.194 s]
[INFO] XiPKI :: example :: lite-caclient-example .......... SUCCESS [  1.210 s]
[INFO] XiPKI :: example :: ocsp-store-example ............. SUCCESS [  0.170 s]
[INFO] XiPKI :: example :: ocsp-store-example-assembly .... FAILURE [  0.035 s]
[INFO] XiPKI :: scep-example .............................. SKIPPED
[INFO] XiPKI :: dummy-ctlog-server ........................ SKIPPED
[INFO] XiPKI :: assemblies ................................ SKIPPED
[INFO] XiPKI :: features .................................. SKIPPED
[INFO] XiPKI :: feature :: cli ............................ SKIPPED
[INFO] XiPKI :: feature :: qa ............................. SKIPPED
[INFO] XiPKI :: assembly :: xipki-dbtool .................. SKIPPED
[INFO] XiPKI :: assembly :: xipki-cli ..................... SKIPPED
[INFO] XiPKI :: assembly :: xipki-ocsp .................... SKIPPED
[INFO] XiPKI :: assembly :: xipki-ca ...................... SKIPPED
[INFO] XiPKI :: assembly :: xipki-p11proxy ................ SKIPPED
[INFO] XiPKI :: assembly :: xipki-qa 5.3.15-SNAPSHOT ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.873 s
[INFO] Finished at: 2022-01-22T16:02:45+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.0:unpack (copy-war) on project ocsp-store-example-assembly: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ocsp-store-example-assembly
```

Is my process to build the packages wrong. If they are could you please tell me the correct process

**Versions:**

```
$ mvn -v
Apache Maven 3.5.4 (Red Hat 3.5.4-5)
Maven home: /usr/share/maven
Java version: 1.8.0_312, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-348.12.2.el8_5.x86_64", arch: "amd64", family: "unix"
```

```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by xipki** [comment]
Please refer to the "Binaries" block of README.md.

**Comment by jeschero** [comment]
I build xipki successful and i am now in the process to create the key but get this error message `Error executing command: sun.security.pkcs11.wrapper.PKCS11.getInstance(Ljava/lang/String;Ljava/lang/String;Lsun/security/pkcs11/wrapper/CK_C_INITIALIZE_ARGS;Z)Lsun/security/pkcs11/wrapper/PKCS11;` 

my pkcs11.json file: [pkcs11-20220123.json](https://github.com/xipki/xipki/files/7920028/pkcs11-20220123.json.txt)


And the scripts: [myca.script](https://github.com/xipki/xipki/files/7920026/myca.script.txt) and [template.ca-conf.json](https://github.com/xipki/xipki/files/7920027/template.ca-conf.json.txt)


The karafa cli logfile: [karaf-cli-20220123.txt](https://github.com/xipki/xipki/files/7920016/karaf-cli-20220123.txt)


With `sudo -u tomcat -- opensc-tool --list-readers` and `sudo -u tomcat -- pkcs11-tool --list-slots` i can see the infos about the nitrokey hsm


**Version**

I used the master branch (01/22/2022) from OpenSC to build the driver

**Comment by xipki** [comment]
Please make sure that your jdk version is supported as specified in readme.

jeschero ***@***.***> schrieb am So., 23. Jan. 2022, 09:05:

**Comment by jeschero** [comment]
I switch from `java-1.8.0-openjdk.x86_64` to `java-11-openjdk.x86_64` which is supported and get a new error:
`Error executing command: 'sun.security.pkcs11.wrapper.PKCS11 sun.security.pkcs11.wrapper.PKCS11.getInstance(java.lang.String, java.lang.String, sun.security.pkcs11.wrapper.CK_C_INITIALIZE_ARGS, boolean)'`

karaf log:
```
2022-01-23T09:47:53,901 | INFO  | pipe-source xipki/ca-setup/myca/myca.script | SourceAction                       75 | 21 - org.apache.karaf.shell.commands - 4.2.14 | Printing file: /usr/local/xipki/xipki-cli-5.3.15-SNAPSHOT/xipki/ca-setup/myca/myca.script
2022-01-23T09:47:54,247 | ERROR | pipe-xi:rsa-p11 --slot ${SLOT} --label ${P11_LABEL} --key-size ${KEY_SIZE} | IaikP11Module                     187 | 49 - org.xipki.security - 5.3.15.SNAPSHOT | unexpected Exception
java.lang.NoSuchMethodError: 'sun.security.pkcs11.wrapper.PKCS11 sun.security.pkcs11.wrapper.PKCS11.getInstance(java.lang.String, java.lang.String, sun.security.pkcs11.wrapper.CK_C_INITIALIZE_ARGS, boolean)'
	at iaik.pkcs.pkcs11.Module.initialize(Module.java:357) ~[!/:?]
	at org.xipki.security.pkcs11.iaik.IaikP11Module.getInstance(IaikP11Module.java:170) [!/:?]
	at org.xipki.security.pkcs11.iaik.IaikP11ModuleFactory.newModule(IaikP11ModuleFactory.java:44) [!/:?]
	at Proxy6f1ab70f_ec0e_4515_a8bf_94f8644d2dfe.newModule(Unknown Source) [?:?]
	at org.xipki.security.pkcs11.P11ModuleFactoryRegisterImpl.getP11Module(P11ModuleFactoryRegisterImpl.java:86) [!/:?]
	at org.xipki.security.pkcs11.P11CryptServiceFactoryImpl.getP11CryptService(P11CryptServiceFactoryImpl.java:126) [!/:?]
	at org.xipki.security.shell.P11Actions$P11SecurityAction.getP11Module(P11Actions.java:714) [!/:?]
	at org.xipki.security.shell.P11Actions$P11SecurityAction.getSlot(P11Actions.java:707) [!/:?]
	at org.xipki.security.shell.P11Actions$EcP11.execute0(P11Actions.java:311) [!/:?]
	at org.xipki.shell.XiAction.execute(XiAction.java:58) [!/:?]
	at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) [!/:4.2.14]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) [!/:4.2.14]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) [!/:4.2.14]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599) [!/:4.2.14]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526) [!/:4.2.14]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415) [!/:4.2.14]
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416) [!/:4.2.14]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) [!/:4.2.14]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) [!/:4.2.14]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-01-23T09:47:54,261 | INFO  | pipe-xi:rsa-p11 --slot ${SLOT} --label ${P11_LABEL} --key-size ${KEY_SIZE} | IaikP11Module                     222 | 49 - org.xipki.security - 5.3.15.SNAPSHOT | close pkcs11 module: default
2022-01-23T09:47:54,275 | ERROR | Karaf local console user karaf | ShellUtil                         152 | 22 - org.apache.karaf.shell.core - 4.2.14 | Exception caught while executing command
org.xipki.security.pkcs11.P11TokenException: 'sun.security.pkcs11.wrapper.PKCS11 sun.security.pkcs11.wrapper.PKCS11.getInstance(java.lang.String, java.lang.String, sun.security.pkcs11.wrapper.CK_C_INITIALIZE_ARGS, boolean)'
	at org.xipki.security.pkcs11.iaik.IaikP11Module.getInstance(IaikP11Module.java:189) ~[?:?]
	at org.xipki.security.pkcs11.iaik.IaikP11ModuleFactory.newModule(IaikP11ModuleFactory.java:44) ~[?:?]
	at Proxy6f1ab70f_ec0e_4515_a8bf_94f8644d2dfe.newModule(Unknown Source) ~[?:?]
	at org.xipki.security.pkcs11.P11ModuleFactoryRegisterImpl.getP11Module(P11ModuleFactoryRegisterImpl.java:86) ~[?:?]
	at org.xipki.security.pkcs11.P11CryptServiceFactoryImpl.getP11CryptService(P11CryptServiceFactoryImpl.java:126) ~[?:?]
	at org.xipki.security.shell.P11Actions$P11SecurityAction.getP11Module(P11Actions.java:714) ~[?:?]
	at org.xipki.security.shell.P11Actions$P11SecurityAction.getSlot(P11Actions.java:707) ~[?:?]
	at org.xipki.security.shell.P11Actions$EcP11.execute0(P11Actions.java:311) ~[?:?]
	at org.xipki.shell.XiAction.execute(XiAction.java:58) ~[?:?]
	at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) ~[?:?]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) ~[?:?]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by xipki** [comment]
Very strange. Please execute the command `info` in the karaf shell and provide the output here.

**Comment by jeschero** [comment]
```
karaf@root()> info
Karaf
  Karaf version               4.2.14
  Karaf home                  /usr/local/xipki/xipki-cli-5.3.15-SNAPSHOT
  Karaf base                  /usr/local/xipki/xipki-cli-5.3.15-SNAPSHOT
  OSGi Framework              org.apache.felix.framework-5.6.12

JVM
  Java Virtual Machine        OpenJDK 64-Bit Server VM version 11.0.13+8-LTS
  Version                     11.0.13
  Vendor                      Red Hat, Inc.
  Pid                         4428
  Uptime                      43.853 seconds
  Process CPU time            29.750 seconds
  Process CPU load            0.00
  System CPU load             0.00
  Open file descriptors       95
  Max file descriptors        262,144
  Total compile time          26.407 seconds
Threads
  Live threads                42
  Daemon threads              19
  Peak                        52
  Total started               71
Memory
  Current heap size           36,789 kbytes
  Maximum heap size           722,944 kbytes
  Committed heap size         84,992 kbytes
  Pending objects             0
  Garbage collector           Name = 'G1 Young Generation', Collections = 21, Time = 0.410 seconds
  Garbage collector           Name = 'G1 Old Generation', Collections = 0, Time = 0.000 seconds
Classes
  Current classes loaded      7,615
  Total classes loaded        7,615
  Total classes unloaded      0
Operating system
  Name                        Linux version 4.18.0-348.12.2.el8_5.x86_64
  Architecture                amd64
  Processors                  2
```

**Comment by xipki** [comment]
For opendk 11.0.13, as in https://github.com/openjdk/jdk/blob/b34a8c43f17cb76d11f69ad4fc95f75635962c7b/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/wrapper/PKCS11.java#L145, the method does exist.

Could you please upload the jar contains the class sun.security.pkcs11.wrapper.PKCS11? In JDK 8, it is the file `jre/lib/ext/sunpkcs11.jar`.

**Comment by jeschero** [comment]
The `ext` folder not longer exist: [Migrating to JDK 10 from JDK 8](https://docs.oracle.com/javase/10/migrate/toc.htm#JSMIG-GUID-2C896CA8-927C-4381-A737-B1D81D964B7B) so I don't know where to find the jar file.

**Comment by xipki** [comment]
Please switch back to jdk 8, and you should find the jar file.

P.S.: Do you need pkcs#11 for your ocsp responder?

**Comment by jeschero** [comment]
i switch back from from `jdk 11` to `jdk 8`.

```
karaf@root()> info
Karaf
  Karaf version               4.2.14
  Karaf home                  /usr/local/xipki/xipki-cli-5.3.15-SNAPSHOT
  Karaf base                  /usr/local/xipki/xipki-cli-5.3.15-SNAPSHOT
  OSGi Framework              org.apache.felix.framework-5.6.12

JVM
  Java Virtual Machine        OpenJDK 64-Bit Server VM version 25.312-b07
  Version                     1.8.0_312
  Vendor                      Red Hat, Inc.
  Pid                         5698
  Uptime                      32.619 seconds
  Process CPU time            22.680 seconds
  Process CPU load            0.00
  System CPU load             0.00
  Open file descriptors       103
  Max file descriptors        262,144
  Total compile time          13.436 seconds
Threads
  Live threads                41
  Daemon threads              18
  Peak                        51
  Total started               70
Memory
  Current heap size           121,024 kbytes
  Maximum heap size           643,072 kbytes
  Committed heap size         177,152 kbytes
  Pending objects             0
  Garbage collector           Name = 'PS Scavenge', Collections = 10, Time = 0.181 seconds
  Garbage collector           Name = 'PS MarkSweep', Collections = 2, Time = 0.221 seconds
Classes
  Current classes loaded      7,059
  Total classes loaded        7,059
  Total classes unloaded      0
Operating system
  Name                        Linux version 4.18.0-348.12.2.el8_5.x86_64
  Architecture                amd64
  Processors                  2
```

The [sunpkcs11.jar.zip](https://github.com/xipki/xipki/files/7920385/sunpkcs11.jar.zip) file.


P.S.: If it possible but i can't even create the pkcs#11 certificate for the ca at the moment.

**Comment by xipki** [comment]
Found the reason. You use red hat JDK, which modifies the PKCS11.getInstance() method. I will add support in the next version (in the xipki/pkcs11wrapper project, not here xipki/xipki).

If allowed, please use JDK of other vendors like oracle or zulu (https://www.azul.com/downloads/).

**Comment by xipki** [comment]
Did you try the up-to-date master branch? Can you verify whether it works?

**Comment by xipki** [comment]
I tested with the sunpkcs11.jar uploaded in this thread and it worked. So I close this issue.
