### ISSUE TITLE
CA fails to start due to soft reference cleanup failure

### ISSUE THREAD

**Issue by zeridon** [xipki/xipki#267]
Environment:

 * Ubuntu 22.04
 * Tomcat/9.0.58
 * openjdk version "11.0.17" 2022-10-18 (attempted with openjdk17 too)

Install method: Java and tomcat installed from packages, xipki-ca unpacked in /var/lib/tomcat9

Expected: CA application starts

Actual:

```
tomcat9[110704]: One or more Filters failed to start. Full details will be found in the appropriate container log file
tomcat9[110704]: Context [/ca] startup failed due to previous errors
tomcat9[110704]: The web application [ca] appears to have started a thread named [tinylog-WritingThread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
tomcat9[110704]:  java.base@11.0.17/java.lang.Thread.sleep(Native Method)
tomcat9[110704]:  org.tinylog.core.WritingThread.run(WritingThread.java:72)
tomcat9[110704]: Failed to clear soft references from ObjectStreamClass$Caches for web application [ca]
tomcat9[110704]: java.lang.ClassCastException: class java.io.ObjectStreamClass$Caches$1 cannot be cast to class java.util.Map (java.io.ObjectStreamClass$Caches$1 and java.util.Map are in module java.base of loader 'bootstrap')
tomcat9[110704]:     at org.apache.catalina.loader.WebappClassLoaderBase.clearCache(WebappClassLoaderBase.java:2325)
tomcat9[110704]:     at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches(WebappClassLoaderBase.java:2300)
tomcat9[110704]:     at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1669)
tomcat9[110704]:     at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1597)
tomcat9[110704]:     at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:463)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
tomcat9[110704]:     at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5515)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
tomcat9[110704]:     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
tomcat9[110704]:     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
tomcat9[110704]:     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
tomcat9[110704]:     at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1024)
tomcat9[110704]:     at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
tomcat9[110704]:     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
tomcat9[110704]:     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tomcat9[110704]:     at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
tomcat9[110704]:     at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
tomcat9[110704]:     at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:825)
tomcat9[110704]:     at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:475)
tomcat9[110704]:     at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
tomcat9[110704]:     at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
tomcat9[110704]:     at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
tomcat9[110704]:     at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
tomcat9[110704]:     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
tomcat9[110704]:     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
tomcat9[110704]:     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tomcat9[110704]:     at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
tomcat9[110704]:     at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
tomcat9[110704]:     at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
tomcat9[110704]:     at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
tomcat9[110704]:     at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
tomcat9[110704]:     at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
tomcat9[110704]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
tomcat9[110704]:     at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
tomcat9[110704]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tomcat9[110704]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tomcat9[110704]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tomcat9[110704]:     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tomcat9[110704]:     at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
tomcat9[110704]:     at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:480)
tomcat9[110704]: Deployment of web application archive [/var/lib/tomcat9/webapps/ca.war] has finished in [1,970] ms
tomcat9[110704]: Deploying web application directory [/var/lib/tomcat9/webapps/ROOT]
tomcat9[110704]: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
tomcat9[110704]: Deployment of web application directory [/var/lib/tomcat9/webapps/ROOT] has finished in [773] ms
tomcat9[110704]: Starting ProtocolHandler ["http-nio-8080"]
tomcat9[110704]: Server startup in [2925] milliseconds
```

**Comment by zeridon** [comment]
And to correct myself ... this comes from `XIPKI_BASE` not being properly set

by default in `setenv.sh` there is `export JAVA_OPTS="${JAVA_OPTS} -DXIPKI_BASE=${CATALINA_HOME}/xipki"`

Changing to `export JAVA_OPTS="${JAVA_OPTS} -DXIPKI_BASE=${CATALINA_BASE}/xipki"`

it works
