### ISSUE TITLE
Error while generating cert.der in xipki: 6.3.0v

### ISSUE THREAD

**Issue by sanjiths** [xipki/xipki#304]
I have installed xipki-6.3.0v and was able to fetch cacert.der using the following commands:
1.CA_URL="https://localhost:8443/rest/ca"
2.OPTS="--insecure --user user1:password1"
3.Generated cacert.der using command:
curl --insecure --output /tmp/temp/cacert.der "${CA_URL}/cacert"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   398  100   398    0     0    805      0 --:--:-- --:--:-- --:--:--   804
4)Facing below error in the rest.log while generating cert.der:
#curl --insecure --user user1:password1 --header "Content-Type: application/pkcs10" --data-binary @/tmp/temp/test.csr --output /tmp/temp/cert.der "${CA_URL}/enroll-cert?profile=tls"

```
2023-11-10 15:44:15,382 INFO o.x.c.g.GatewayUtil [http-nio-127.0.0.1-8181-exec-7] rest-gw;      status: SUCCESSFUL      duration: 3     ca: ca  event_type: cacert
2023-11-10 15:44:15,383 ERROR o.x.c.g.r.RestResponder [http-nio-127.0.0.1-8181-exec-8] Throwable thrown, this should not happen!
java.lang.NullPointerException: csr may not be null
        at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
        at org.xipki.util.Args.notNull(Args.java:114) ~[util-6.3.0.jar:?]
        at org.xipki.ca.gateway.GatewayUtil.verifyCsr(GatewayUtil.java:41) ~[gateway-common-6.3.0.jar:?]
        at org.xipki.ca.gateway.rest.RestResponder.enrollCerts(RestResponder.java:507) ~[classes/:?]
        at org.xipki.ca.gateway.rest.RestResponder.service(RestResponder.java:326) ~[classes/:?]
        at org.xipki.ca.gateway.rest.servlet.HttpRestServlet.service0(HttpRestServlet.java:64) ~[classes/:?]
        at org.xipki.ca.gateway.rest.servlet.HttpRestServlet.doGet(HttpRestServlet.java:47) ~[classes/:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:529) ~[servlet-api.jar:[4.0.FR](http://4.0.fr/)]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:[4.0.FR](http://4.0.fr/)]
        at org.xipki.ca.gateway.rest.servlet.ProtocolServletFilter.doFilter(ProtocolServletFilter.java:80) ~[classes/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.78]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.78]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:9.0.78]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:9.0.78]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[catalina.jar:9.0.78]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:9.0.78]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673) ~[catalina.jar:9.0.78]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:9.0.78]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:9.0.78]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:9.0.78]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-coyote.jar:9.0.78]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:9.0.78]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-coyote.jar:9.0.78]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-coyote.jar:9.0.78]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:9.0.78]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.78]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.78]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.78]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-11-10 15:44:15,384 WARN o.x.c.g.GatewayUtil [http-nio-127.0.0.1-8181-exec-8] rest-gw;      status: FAILED  duration: 0     ca: ca  event_type: enroll-cert requestor: user1        message: internal error
```

**Comment by sanjiths** [comment]
[Uploading rest.log…]()

**Comment by xipki** [comment]
The reason is you sent the data via HTTP GET. It shall be HTTP POST. Please try with option "-X POST".

**Comment by xipki** [comment]
Any update?

**Comment by sanjiths** [comment]
Certs are fetched after changing to HTTP POST. Pls resolve this issue.

Thanks
Sanjith S
