### ISSUE TITLE
Error "org.xipki.ca.sdk.SdkErrorResponseException: NOT_PERMITTED, no requestor specified"

### ISSUE THREAD

**Issue by sanjiths** [xipki/xipki#325]
I have performed rootCA configuration with xipki-6.5.1v and was able to fetch the certs & crl using rest-gateway interface with "requestor1"
I have upgraded my CA application with xipki-6.5.3v using rest-gateway interface with "requestor2". I have added the requestor2 and update the requestor using karaf commands.

```
karaf@root()> ca:requestor-add --name requestor2 --cert /tmp/gateway/xipki/keycerts/ra-sdk-client-cert.pem      
added CMP requestor requestor2
karaf@root()> ca:requestor-up --name requestor2 --cert /tmp/gateway/xipki/keycerts/ra-sdk-client-cert.pem  
updated requestor requestor2
```

I am facing below error while trying to fetch the cert now:
```
sh-5.1$ tail -f /tmp-gateway/logs/gateway.log
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388) [tomcat-coyote.jar:9.0.91]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.91]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936) [tomcat-coyote.jar:9.0.91]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-coyote.jar:9.0.91]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.91]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) [tomcat-util.jar:9.0.91]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.91]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) [tomcat-util.jar:9.0.91]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
2024-11-18 19:49:27,624 WARN o.x.c.g.GatewayUtil [http-nio-8082-exec-7] rest-gw;        status: FAILED  duration: 2     ca: ca  event_type: cacert      message: internal error



2024-11-18 19:49:32,690 ERROR o.x.c.g.r.RestResponder [http-nio-8082-exec-8] Throwable thrown, this should not happen!
org.xipki.ca.sdk.SdkErrorResponseException: NOT_PERMITTED, no requestor specified
        at org.xipki.ca.sdk.SdkClient.send(SdkClient.java:120) ~[ca-sdk-6.5.3.jar:?]
        at org.xipki.ca.sdk.SdkClient.cacert(SdkClient.java:137) ~[ca-sdk-6.5.3.jar:?]
        at org.xipki.ca.gateway.rest.RestResponder.service(RestResponder.java:337) [gateway-6.5.3.jar:?]
        at org.xipki.ca.gateway.rest.RestHttpServlet.service0(RestHttpServlet.java:65) [gateway-6.5.3.jar:?]
        at org.xipki.ca.gateway.rest.RestHttpServlet.service(RestHttpServlet.java:50) [gateway-6.5.3.jar:?]
        at org.xipki.ca.gateway.GatewayHttpFilter.doFilter(GatewayHttpFilter.java:349) [gateway-6.5.3.jar:?]
        at org.xipki.servlet3.ServletFilter.doFilter(ServletFilter.java:64) [servlet3-common-6.3.4.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [catalina.jar:9.0.91]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [catalina.jar:9.0.91]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) [catalina.jar:9.0.91]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:9.0.91]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) [catalina.jar:9.0.91]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:9.0.91]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:9.0.91]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) [catalina.jar:9.0.91]
        at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:287) [catalina.jar:9.0.91]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.91]
        at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:532) [catalina.jar:9.0.91]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.91]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) [catalina.jar:9.0.91]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388) [tomcat-coyote.jar:9.0.91]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.91]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936) [tomcat-coyote.jar:9.0.91]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-coyote.jar:9.0.91]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.91]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) [tomcat-util.jar:9.0.91]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.91]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) [tomcat-util.jar:9.0.91]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
2024-11-18 19:49:32,690 WARN o.x.c.g.GatewayUtil [http-nio-8082-exec-8] rest-gw;        status: FAILED  duration: 6     ca: ca  event_type: cacert      message: internal error

```

**Comment by sanjiths** [comment]
I have used the same ra-sdk cert files `xipki-gateway/tomcat/xipki/keycerts/ra-sdk-client-cert.pem` and `xipki-gateway/tomcat/xipki/keycerts/ra-sdk-client.p12 files & gateway.json in 6.5.1 and 6.5.3 packages.

Configured same truststorePassword & certificateKeystorePassword in "xipki-install/xipki-gateway/tomcat8on/conf/server.xml" in both 6.5.1 and 6.5.3 packages & in `xipki-gateway/tomcat/xipki/etc/gateway.json`

**Comment by sanjiths** [comment]
can you pls close this isue? Issue is resolved after updating the requestor  with same cert used in 6.5.1v
