### ISSUE TITLE
Build with tests failes

### ISSUE THREAD

**Issue by paulvi** [xipki/xipki#64]
mvn clean install -Pdist

fails on Windows #61, but not sure if it is the reason

```
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ password ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.xipki.password.test.PBEWithHmacSHA256AndAES256Test
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.883 s <<< FAILURE! - in org.xipki.password.test.PBEWithHmacSHA256AndAES256Test
[ERROR] decrypt(org.xipki.password.test.PBEWithHmacSHA256AndAES256Test)  Time elapsed: 0.842 s  <<< ERROR!
java.security.InvalidKeyException: Illegal key size
        at org.xipki.password.test.PBEWithHmacSHA256AndAES256Test.decrypt(PBEWithHmacSHA256AndAES256Test.java:57)

[ERROR] encrypThenDecrypt(org.xipki.password.test.PBEWithHmacSHA256AndAES256Test)  Time elapsed: 0 s  <<< ERROR!
java.security.InvalidKeyException: Illegal key size
        at org.xipki.password.test.PBEWithHmacSHA256AndAES256Test.encrypThenDecrypt(PBEWithHmacSHA256AndAES256Test.java:43)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   PBEWithHmacSHA256AndAES256Test.decrypt:57 ? InvalidKey Illegal key size
[ERROR]   PBEWithHmacSHA256AndAES256Test.encrypThenDecrypt:43 ? InvalidKey Illegal key s...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] XiPKI :: xipki-parent .............................. SUCCESS [  1.476 s]
[INFO] XiPKI :: scep-common ............................... SUCCESS [  4.762 s]
[INFO] XiPKI :: scep-server-emulator ...................... SUCCESS [  1.416 s]
[INFO] XiPKI :: scep-client ............................... SUCCESS [ 23.397 s]
[INFO] XiPKI :: common .................................... SUCCESS [  3.543 s]
[INFO] XiPKI :: password .................................. FAILURE [  2.405 s]
[INFO] XiPKI :: security .................................. SKIPPED

```

**Comment by xipki** [comment]
This test failure is due to the Jurisdiction Policy of Oracle JDK. One needs either JDK 8 build 162+ or install the "Unlimited Strength Jurisdiction Policy Files".

I will skip the JUnit tests if such limitation exitst in the build process, but for Runtime you still need the unlimited policy.

**Comment by paulvi** [comment]
OK, what I have is `java version "1.8.0_144"`, so just to upgrade to latest Java 8 release

**Comment by paulvi** [comment]
It is already said in REAME so
