### ISSUE TITLE
Unable to enroll CSR generated using keytool

### ISSUE THREAD

**Issue by hkalina** [xipki/xipki#71]
**When trying to enroll CSR generated using keytool in default setup (cacert-present), xipki reports invalid CSR request - "unknown tag 13 encountered":**
```
keytool -genkey -alias loc -keyalg RSA -keysize 2048 -keystore localhost.jks -dname "CN=localhost,O=xipki,C=DE"
keytool -certreq -alias loc -keyalg RSA -file localhost.csr -keystore localhost.jks
```
```
karaf@root()> ca:enroll-cert --out signed.crt --csr localhost.csr --ca myca1 --profile ocsp
Error executing command: invalid CSR request. ERROR: failed to construct sequence from byte[]: unknown tag 13 encountered
karaf@root()> log:exception-display
org.xipki.ca.server.mgmt.api.CaMgmtException: invalid CSR request. ERROR: failed to construct sequence from byte[]: unknown tag 13 encountered
	at org.xipki.ca.server.impl.CaManagerImpl.generateCertificate(CaManagerImpl.java:2107) ~[?:?]
	at org.xipki.ca.server.mgmt.shell.cert.EnrollCertAction.execute0(EnrollCertAction.java:86) ~[?:?]
	at org.xipki.shell.XiAction.execute(XiAction.java:57) ~[?:?]
	at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) ~[?:?]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) ~[?:?]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:571) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:497) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:386) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:417) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```
Used CSR file:
```
-----BEGIN NEW CERTIFICATE REQUEST-----
MIICpjCCAY4CAQAwMTELMAkGA1UEBhMCREUxDjAMBgNVBAoTBXhpcGtpMRIwEAYD
VQQDEwlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCx
qhmH1sYZjSpgKrQ9/CoXwvUjmbLU1cTRhCIJ86qDrsuA/bhMsEdneO6ZI5lJwgmp
DhzVaFIH41+8SG6qcVTbPrGwHasPAklFGxNHkliGtDRQduoWhvGYeCDHtkn7KlZF
WBMzpN5STWaNHKEpsrqEyGCZ7hM0YGNEmE556z0Azrjf9f6o1zwlwgtABNqzXLju
OrmBdL7CG8PO+EcZcukSY9SRn3M8wrHXmye6ilmOEEwi4QFTofBRAcMUgEUnTgih
uFGr+OoE/LTI1U4cV4mAUxleshQ8xnRpB1aP5I1TIPKqvhXz3YeMrd9dAna2/JOt
kkiNoB5+7NZBYRKjBqnPAgMBAAGgMDAuBgkqhkiG9w0BCQ4xITAfMB0GA1UdDgQW
BBTaYbJSTSoS8ctyr+1/KhIWLcsyAjANBgkqhkiG9w0BAQsFAAOCAQEAK7i9OaZO
wfpkJ0yOldNBqjduzMHX2MSYnjFwH94geWM/YmSNMQ29pDOhG2i9mr3rjD0uMelz
OQe4hwJ1CsthO9yeahbVJtm/mCbCoxFZRtCByqC5KZt/YxihdBvNOGFmBDe2AVPG
sfGedocQwXbA/EyXyy6fBW9+tx9zUAD5jaKEx3g73QnN1d8MMPbg9Lijp/nGKtiC
/YuvuIdLkvvoECENo43YRPIa46N+e40GzifXBZHwzGSOBnRYyU9ARupasgjy+l/3
sdotGOKed4qb61Ot1Tfjo5360gotVPZbPpQUga0w3mhrW2gYI4uM9EK4FxeZg/L/
FDTYWx9Eat2nXw==
-----END NEW CERTIFICATE REQUEST-----
```

**Comment by hkalina** [comment]
Sorry, my fault - the problem is encoding of CSR:
* xipki expects binary DER
* keytool generates base64 encoded PEM
After **base64 decoding** enrollment succeed :)

Maybe would be welcome:
* To include PEM format support
* To add simple keytool based example into README/commands.md
