### ISSUE TITLE
can't initizial self-signal ca

### ISSUE THREAD

**Issue by mr-tan4** [xipki/xipki#73]
Error executing command: could not load configuration xipki/setup/cacert-none/ca-conf.xml, error: could not add CMP requestor requestor-mac1

**Comment by xipki** [comment]
Please provide more information: xipki version, jdk version, OS and log file data/log/karaf.log. And if possible, also steps to reproduce the error.

**Comment by mr-tan4** [comment]
1. 1. xipki version:xipki-pki-4.0.1-SNAPSHOT,
2. 2. os:mac osx
3. 3. java version: "1.8.0_51"
4. karaf log file:[https://github.com/mr-tan4/error/blob/master/karaf.log](url)
5. error steps:[https://github.com/mr-tan4/error/blob/master/error.png](url)

**Comment by mr-tan4** [comment]
the ocsp server can't started ,and not find ocsp.p12 file in xipki/setup/keycerts/

**Comment by mr-tan4** [comment]
I tried to replace the h2 database with mysql, but there was a new problem.
After running the 
> source xipki/setup/cacert-none/setup-rsa-p12.script  command
 
an error occurred:

> Error executing command: could not restart CA system, error: could not restart CA system

the karaf error log:

> org.xipki.shell.CmdFailure: could not restart CA system, error: could not restart CA system
	at org.xipki.ca.server.mgmt.shell.CaSystemRestartAction.execute0(CaSystemRestartAction.java:40) ~[?:?]
	at org.xipki.shell.XiAction.execute(XiAction.java:61) ~[?:?]
	at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) ~[?:?]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) ~[?:?]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526) ~[?:?]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: org.xipki.ca.server.mgmt.api.CaMgmtException: could not restart CA system
	at org.xipki.ca.server.impl.CaManagerImpl.logAndCreateException(CaManagerImpl.java:3355) ~[?:?]
	at org.xipki.ca.server.impl.CaManagerImpl.restartCaSystem(CaManagerImpl.java:604) ~[?:?]
	at org.xipki.ca.server.mgmt.shell.CaSystemRestartAction.execute0(CaSystemRestartAction.java:38) ~[?:?]
	... 14 more
2018-10-11T13:57:43,298 | ERROR | Blueprint Extender: 3 | BlueprintContainerImpl            376 | 20 - org.apache.aries.blueprint.core - 1.9.0 | Unable to start blueprint container for bundle org.xipki.ocsp-server-netty/4.0.1.SNAPSHOT due to unresolved dependencies [(objectClass=org.xipki.ocsp.api.OcspServer)]
java.util.concurrent.TimeoutException: null
	at org.apache.aries.blueprint.container.BlueprintContainerImpl$1.run(BlueprintContainerImpl.java:373) [20:org.apache.aries.blueprint.core:1.9.0]
	at org.apache.aries.blueprint.utils.threading.impl.DiscardableRunnable.run(DiscardableRunnable.java:45) [20:org.apache.aries.blueprint.core:1.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
